### ISSUE TITLE
Mechanic and Jeweler

### ISSUE THREAD

**Issue by bbotelho3** [RadGH/RadGH-s-Dwarf-Therapist-Professions#1]
Hello,

Great work on the custom professions, I have been using them and they are great.

I noticed some things though: I couldn't find a specialized mechanic profession. Maybe you don't use them often enough?

There's no exclusive Gem Cutter profession. The game has a profession called Jeweler, which I think the Gem Setter specialized profession could be renamed to.

When I import the file, it imported an UNKNOWN profession, not sure if it's a bug in the Dwarf Therapist or the file actually has that in it.

There's a military called @ Scout, which is not included in the README. I assume it's to be used for scout missions or scouting the map?

Anyway, just some suggestions. Thanks for creating the project.

**Comment by RadGH** [comment]
Hey @bzxbot, thanks for the feedback!

1. I added scout to the readme, Not sure I missed that!
2. The UNKNOWN profession was a Deconstructor that I had deleted, or so I thought. Apparently the definition was still in the export. I also discovered that  Dwarf Therapist will export/import everything in the list even if you uncheck some items, so I [reported that issue](https://github.com/Dwarf-Therapist/Dwarf-Therapist/issues/95).
3. I added Gem Cutter, just an oversight. I definitely use that role but I must not have saved it.
4. I added a Mechanic. I haven't used a dedicated one.

I know these are easy to fix yourself, so I appreciate you letting me know about them so I can improve this for others :)

Let me know if you have any other suggestions/corrections!
