### ISSUE TITLE
Missing a profession for Fishing

### ISSUE THREAD

**Issue by ronanversendaal** [RadGH/RadGH-s-Dwarf-Therapist-Professions#2]
Hey I came across your professions and they are very neat. I searched for a fishing related Profession and although there are a few with dissecting/cleaning, I was not able to find one with the actual fishing 
labor in it. 

I understand they should be in one of the 1 and 2 level professions, I wondered where you would add these professions to if you needed a fisher, or maybe a new Profession?

**Comment by RadGH** [comment]
@ronanversendaal Hey thanks for pointing that out. Actually I just don't use fishing and never thought of it as a profession.

The tier 1 professions are pretty generic so you could add it to the grower role, for example. You can save that to the original profession by assigning it to the dwarf, then right-click and save the custom profession (I forget what exactly that option is called).

For tier 2 you could make a dedicated fisherman role by assigning the "2: Cook" profession and then changing Cooking skill to Fishing, then right click and use "New custom profession from this dwarf".

I'll add those in next time I get in to Dwarf Fortress again.

**Comment by ronanversendaal** [comment]
Thanks for the answer ! I'll make sure to try it out.
